apiVersion: v1
kind: Namespace
metadata:
  name: demo-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: 637423268505.dkr.ecr.us-east-1.amazonaws.com/uptime-kuma:latest # <--- CHECK THIS
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: data
          mountPath: "/app/data"
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dvwa
  namespace: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dvwa
  template:
    metadata:
      labels:
        app: web-dvwa
    spec:
      containers:
      - name: web-dvwa
        image: 637423268505.dkr.ecr.us-east-1.amazonaws.com/web-dvwa:latest # <--- CHECK THIS
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-dvwa
  namespace: demo-apps
spec:
  selector:
    app: web-dvwa
  ports:
  - port: 80
    targetPort: 80
